import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread("shapes.png")
if img is None:
    raise FileNotFoundError("Image not found. Make sure 'shapes.png' is in the same folder.")
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
lower_blue = np.array([100, 100, 50])
upper_blue = np.array([130, 255, 255])
lower_red1 = np.array([0, 100, 50])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 100, 50])
upper_red2 = np.array([180, 255, 255])
blue_mask = cv2.inRange(hsv_img, lower_blue, upper_blue)
red_mask1 = cv2.inRange(hsv_img, lower_red1, upper_red1)
red_mask2 = cv2.inRange(hsv_img, lower_red2, upper_red2)
red_mask = cv2.bitwise_or(red_mask1, red_mask2)
combined_mask = cv2.bitwise_or(blue_mask, red_mask)
blue_result = cv2.bitwise_and(img, img, mask=blue_mask)
red_result = cv2.bitwise_and(img, img, mask=red_mask)
combined_result = cv2.bitwise_and(img, img, mask=combined_mask)
fig, axes = plt.subplots(2, 3, figsize=(12, 8))
axes[0, 0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
axes[0, 0].set_title("Original Image")
axes[0, 0].axis("off")
axes[0, 1].imshow(blue_mask, cmap="gray")
axes[0, 1].set_title("Blue Mask")
axes[0, 1].axis("off")
axes[0, 2].imshow(red_mask, cmap="gray")
axes[0, 2].set_title("Red Mask")
axes[0, 2].axis("off")
axes[1, 0].imshow(cv2.cvtColor(blue_result, cv2.COLOR_BGR2RGB))
axes[1, 0].set_title("Blue Detected")
axes[1, 0].axis("off")
axes[1, 1].imshow(cv2.cvtColor(red_result, cv2.COLOR_BGR2RGB))
axes[1, 1].set_title("Red Detected")
axes[1, 1].axis("off")
axes[1, 2].imshow(cv2.cvtColor(combined_result, cv2.COLOR_BGR2RGB))
axes[1, 2].set_title("Combined Detected")
axes[1, 2].axis("off")
plt.tight_layout()
plt.show()